### ISSUE TITLE
Calculation comparison?

### ISSUE THREAD

**Issue by TMeierotto** [agrahamg/VWBuybackCalculator#3]
When I run the calculation on your page here: https://agrahamg.github.io/VWBuybackCalculator/ I get $19,157 for car and $5,682 for restitution. There are some deductions as well. Totals are buyback = $18,667 & modification = $5,602. My issue is when I do the calculations on the vw claim portal here https://claims.vwgoa.com/#/ I get these values. $12,800 for car and $2,773.37 for restitution. So from VW's site I get buyback = $15,573.37 & $2,773.37 for restitution. Who has the incorrect formula? What am I missing? 
Here are my exact details:
State: IA
Model: Jetta
Year: 2012
Trim: Sedan 4D TDI
Options: Fender Stereo System, Power Sunroof
Current Mileage: 85,300
Months since Sept 2015: 11

**Comment by TMeierotto** [comment]
When I calculate here https://byebyetdi.us I get buyback = $18,347 & modification = $5,547. Trying to see if VW has an issue?

**Comment by jcwillo** [comment]
Same discrepancy for me.  Car value on this is $13,400;  VWsettlement site says car value is $8K and change, mostly due to the mileage deduction I assume.  Big difference.  thanks

**Comment by divanoff** [comment]
Not sure what you guys are referring to. If I use the tables on vwcourtsettlement.com and this tool I get the same result. Unfortunately, on https://claims.vwgoa.com/ I am past the calculation step but from memory I think it was the same number.

**Comment by jcwillo** [comment]
Thanks Dimo.... I did my calcs on my 2010 Sportwagen from the Court
Settlement FTC documents (Attachments 1A and 2A for my wagen) and got a
$15,407 gross buyback figure, less $1680 mileage and $750 manual trans
deductions, for net buyback of $12,977.  Restitution is min $5100.  My
total should be $18,077.  That's what I'm going with to VW.
Appreciate the information on the site, really helpful.
Jeff

**Comment by divanoff** [comment]
Sounds about right. Just compare the numbers when you get the offer from them. I called 844-98-CLAIM today and finally got to talk to someone. They said they have to send an offer in 20 business days from the date you uploaded the license, registration, and consent form (if you have a loan) if it's after Oct 25. If you uploaded them before Oct 25 then it's 20 business days from Oct 25. They said they haven't sent any offers yet so they don't know how long it will take for them to take the car from the time you return the signed offer. I am really hoping before the holidays at this point but I wish they were a little more transparent and organized. Right now, it's impossible to make plans for a replacement vehicle and all while still making payments on this one. My fifth VW and second TDI.

Sorry, didn't mean to vent here. Just thought I'd share the info they gave me on the phone today.

Good luck!

**Comment by jcwillo** [comment]
No problem Dimo, thanks again for this add'l info.  I filed my claim online
on Saturday the 29th.  I was ready to buy my replacement vehicle on Sunday
but someone else bought it out from under me.  Maybe it's a good thing
since I was planning on an early Nov sell back to VW.  I'll wait til I hear
back from VW now, hopefully around Nov 18 or so.  Thanks again, good luck
to you too!
Jeff

**Comment by TMeierotto** [comment]
Is it possible to be removed from this email chain?

**Comment by agrahamg** [comment]
The price on VW's claims website will always be the final price you would receive. This tool is only based off of the initial documents released. Hopefully by this time this has all been sorted out for you. 

If anyone is still getting email chains on this you can remove them by unsubscribing in your github settings, but this should be the last email you would get.
