### ISSUE TITLE
FTC Changes To Calculation

### ISSUE THREAD

**Issue by JC2009** [agrahamg/VWBuybackCalculator#4]
Hi:

It appears that your calculator is calculating the correct adjusted mileage, however there is a 'Further Adjustment' if the modification is less than 5100.  Can you please take a look at this?

See bottom of page 2 here: https://www.ftc.gov/sites/default/files/pdf/att._2b_-_beetle_and_jetta_mileage_table.pdf

I see an 'adjustment' on your calculation page, but it appears to be way too low.  Is it simply 5100 minus the mileage adjustment if the mileage adjustment is < 5100?

Thanks,

Jim

**Comment by agrahamg** [comment]
Hi Jim, 

Sorry for the late replay. It helps me to figure out what is wrong if you also give the model and any other inputs you might have used when you found the value you believe to be incorrect.

**Comment by JC2009** [comment]
Well, your amount matches what I got at settlement last night (or should get when they get around to it).  I was just having difficulty arriving at the adjustment portion.  Forgot the column B (modification) adjustment for the sunroof.  Thanks again!
